Ensure prop errors are passed to custom inputs
langleyfoxall/react-dynamic-form-builder pull request #19
Opened 2019-02-04 13:12 UTC by robmilward

This commit ensures that custom prop based validation errors are passed to custom rendered inputs. Previously only the validation errors stored in the form builders state were considered.

2019-02-05 07:16 UTC, dextermb requested changes
Minor changes required. This would also clash with #18 as `snake_case` variables were removed.

2019-02-05 07:16 UTC, dextermb commented on src/DynamicFormBuilder.jsx
> +        const validationError = this.state.validation_errors[inputName];
Our internal JS standards say that objects (primarily `state` and `props`) should be deconstructed, for example:
```js
const { validation_errors } = this.state;
```

2019-02-05 07:16 UTC, dextermb commented on src/DynamicFormBuilder.jsx
> +        const propError = this.props.formErrors[inputName];
Our internal JS standards say that objects (primarily `state` and `props`) should be deconstructed, for example:
```js
const { formErrors } = this.props;
```

2019-02-26 08:59 UTC, NilesB approved these changes

2019-02-26 09:04 UTC, dextermb approved these changes

2019-02-26 09:05 UTC, NilesB approved these changes

2019-02-26 09:06 UTC, merged